version: "3.7"
services:

  main_telebot:
    image: python:3.8.12-buster
    build:
      context: ./dockerfile_telebot
    restart: always
    container_name: "main_telebot"
    volumes:
      # - ${WD}/postgress_db/scripts/:/docker-entrypoint-initdb.d/
      - ${WD}:/root
    links:
      - postgres_telebot
    working_dir: /root
    command: bash -c "python3 bot.py --config "config_docker.json" && tail -F anything"

  postgres_telebot:
    image: postgres
    restart: always
    container_name: "postgres_telebot"
    environment:
      - POSTGRES_USER=guinmoon
      - POSTGRES_PASSWORD=moysohn7
      - POSTGRES_DB=telebot
      - PGDATA=/tmp
    ports:
      - 5433:5432
    volumes:
      - ${WD}/storage/db_init/:/docker-entrypoint-initdb.d/
      - ${WD}/storage/pg_data/:/tmp
      # - /Users/guinmoon/dev/telebot/storage/pg_admin:/tmp

volumes:
  tmp:
    external: false
    name: tmp
  # pg_data_:
  #   external: false
  #   name: pg_data
